unit uTST_realCase_001;

{$mode objfpc}{$H+}

interface

uses
      Classes, SysUtils;

implementation

end.

{
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-SourceTREE\textFunction\in0k_lazidesrc_srctree_textfunction__usessection.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_CORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_CORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-wndDEBUG\in0k_lazIdeSRC_DEBUG.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_PATH_FND.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcExt\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_CORE.pas"
}



D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\asd.inc"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_filePkgType_FNK.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_FILE_FND.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_ITEM_4USEs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_ITEM_4INCs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_FILE_FND_abs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\in0k_lazIdeSRC_SETTINGs1.inc"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_PATH_FND_abs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_files4INC.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_rootFILE_FND.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler\srcTree_handler_CORE_fsFILE2CodeBUF.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_Processing.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\srcTree\in0k_lazIdeSRC_CopyRAST_srcTree.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler\srcTree_handler_CORE_makeListFsFILE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler4Build\in0k_lazIdeSRC_srcTree_itmHandler4Build__f8a_usesFile.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler\srcTree_handler_CORE_makeLIST.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeHandler\srcTree_handler_CORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\in0k_lazIdeSRC_srcTree_item_Globals.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_fileSystem_FNK.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_nodeFILE_ADD.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_FILE_FND_rel.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_srchPATH_ADD.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_mainFILE_SET.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_mainFILE_FND.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_mainFILE_GET.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_baseDIR_SET.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_baseDIR_GET.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_baseDIR_FND.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\srcTree\srcTree_FNC.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_PATH_GET_rel.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\FNKs\in0k_lazIdeSRC_srcTree_FNK_PATH_FND_rel.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\in0k_lazIdeSRC_srcTree_item_fsFile.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\in0k_lazIdeSRC_srcTree_item_fsFolder.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_item.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeBuilder\srcTree_builder_4Package.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\treeBuilder\srcTree_builder_CORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE-UI\in0k_lazExt_CopyRAST_cmpTree.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_itemFileSystem.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_PSF_updateInclude.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\Processing_ProjPack\prcNode_XML_Files.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\Processing_ProjPack\prcNode_XML_CompilerOptions_SearchPaths.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_XML_updateLPK_v4.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_core_xmlEdit.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_core_srcEdit.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_XML_updateLPK.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_PSF_updateUses.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_PSF_updateUnit.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_copyFile.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_createTargetDir.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\prcNode_clearTargetDir.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_processingMCHN.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_processingNODE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operationNode_EXECUTOR_Package.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_Node2TEXTs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_TEXTs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_PSF_TEST.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_PSF_updateUsesMain.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_PSF_updateUnit.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_copyFiles.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_createTargetDirs.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\lazExt_CopyRAST_operation_clearTargetDir.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\OperationNODEs\Processing_CORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Forms\lazExt_CopyRAST_FuckUpForm.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\in0k_lazIdeSRC_SETTINGs.inc"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node_ROOT_project.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-FuckUpForm\in0k_lazIdeSRC_FuckUpForm_01.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node_ROOT_package.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-SourceTREE\CORE\in0k_lazIdeSRC_srcTree_CORE_fromIDEProcs_FNK.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node_ROOT.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node_Folder.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node_File.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Nodes\lazExt_CopyRAST_node.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Forms\lazExt_CopyRAST_wndProject.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Forms\lazExt_CopyRAST_wndPackage.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\lazExt_CopyRAST_StrConsts.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\lazExt_CopyRAST.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcPKG\Forms\lazExt_CopyRAST_wndCORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\srcEXT\in0k-lazarusIdeSRC-ExpertCORE\in0k_lazIdeSRC_ExpertCORE.pas"
D:\!PROGECTs\!in0k\in0k_LazIdeEXT_CopyRAST\REG.pas"

